template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:
  - name: approval_pipe
    steps:
      - name: sample_test
        type: Bash
        configuration:
          requiresApproval:
            timeoutSeconds: 86400
            approvers:
              - admin
            notifications:
              - integrationName: {{ .Values.myRepo.slackIntegration }}
        execution:
          onStart:
            - echo "OnStart"
          onExecute:
            - echo "OnExecute"
          onSuccess:
            - echo "OnSuccess"